# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.hostmanager.enabled = true
  config.hostmanager.include_offline = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  NodeCount = 1

  # Spark Nodes
  (1..NodeCount).each do |i|
    config.vm.define "spark#{i}" do |c|
      c.vm.hostname = "spark#{i}"
      c.vm.network "private_network", ip: "192.168.0.1#{i}"
      c.vm.provision "bootstrap", type:"ansible" do |ansible|
        ansible.playbook = "bootstrap.yml"
      end
      c.vm.provision "kafka", type:"ansible" do |ansible|
        ansible.playbook = "spark.yml"
      end  
    end
  end

    config.vm.provision "shell", path: "bootstrap.sh"
end